---
- name: Install mongo repo key
  apt_key: keyserver=keyserver.ubuntu.com id=EA312927

- name: Install mongo repo file
  shell: echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.3 main" | sudo tee /etc/apt/sources.list.d/mongodb-org.list
  become: True

- name: Install mongod package
  package: name=mongodb-org-server state=latest
  become: True

- name: Restart mongod
  service: name=mongod state=restarted enabled=true
